# Generated by Django 4.2.7 on 2023-11-15 17:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Actuador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('ip', models.CharField(max_length=16)),
                ('puerto', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Sensor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Lectura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.FloatField(default=0)),
                ('fecha', models.DateTimeField()),
                ('sensor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='webapp.sensor')),
            ],
        ),
        migrations.CreateModel(
            name='Escritura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.FloatField(default=0)),
                ('fecha', models.DateTimeField()),
                ('actuador', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='webapp.actuador')),
            ],
        ),
        migrations.CreateModel(
            name='ClienteSensor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='webapp.cliente')),
                ('sensor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='webapp.sensor')),
            ],
        ),
        migrations.CreateModel(
            name='ClienteActuador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actuador', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='webapp.actuador')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='webapp.cliente')),
            ],
        ),
    ]
